camera_geometry:
  name: SiPMCamera
  pcm_count: 16
  ddb_count: 4
  channel_count: 9
  expected_packets_per_event: 64
  readout:
    roi_samples: 150
    adc_bits: 14
    lsb_mask: 16383
    channel_zero_dual_map: true
  layout:
    rows: 16
    cols: 16
    ordering: column-major
    pixel_size_mm: 22.1
    pixel_gap_mm: 0.05
  mapping:
    remap_table: null

data:
  #evbfilepath: /home/shahjahan/Desktop/SiPM/Analysis_Pipeline/Codes/data/s0534+2201_339_flashCAL_14122025_2_EVBdata.eve
  #evbfilepath: /home/shahjahan/Desktop/SiPM/Analysis_Pipeline/Codes/data/s0534+2201_405_flashCAL_12012026_2_EVBdata.eve
  #evbfilepath: /home/shahjahan/Desktop/SiPM/Analysis_Pipeline/Codes/data/s0534+2201_455_flashCAL_21012026_2_EVBdata.eve
  evbfilepath: /home/shahjahan/Desktop/SiPM_Analysis_Pipeline/Codes/data/evt.txt

calib:
  drsoffset: /home/shahjahan/Desktop/SiPM/Analysis_Pipeline/Codes/DRS_OFFSET/offsetcal_January13012026.txt 

io:
  output: /home/shahjahan/Desktop/SiPM_Analysis_Pipeline/Codes/output
